== Introduction

This optional word set allows a program to resolve relative paths
and include files with relative paths.

A relative path implies that a "base path" exists
against which the relative path is applied.
Relative paths are only usable when a base path is known.

In some Forth systems a global tuple of base paths is used,
and a relative path in `included` is applied to each of them (in the order)
until the first existing path is found
or until all paths in the tuple have been tried.

This specification assumes only one base path at a time,
associated with the input source.

The underlying concept is similar to the Base URI concept,
see https://www.rfc-editor.org/rfc/rfc3986.html#section-5.1[RFC 3986 / Establishing a Base URI].

In a general case, a base path is an https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier[IRI].

[sidebar]
The only significant difference of IRIs from URIs is that
in IRIs the Universal Character Set (UNICODE) is used,
where URIs were limited to ASCII
and so the https://en.wikipedia.org/wiki/Percent-encoding[percent-encoding]
is used for characters outside the ASCII charset.

If and only if the implied URI scheme of a base path is `file:`
(see https://www.rfc-editor.org/rfc/rfc8089.html[RFC 8089: The "file" URI Scheme]),
its "scheme" and "host" parts may be omitted.
A consequence of this is that only the forward slash is used
as a path segment separator when a URI scheme is omitted,
and effectively a base path is either an absolute IRI or a full path in the local file system.

When using a Windows-like file path for a base path,
the drive letter (e.g., "c:") can be mapped into the first path segment,
and the forward slash "`/`" shall be used as a path segment separator.
Note that the Windows API supports the forward slash as a path segment separator.


In this specification, a base path is formally associated with an input source
and it is *a part of the input source specification _state_*.

Some optimizations are possible due to the fact that
a program can obtain the base path of the current input source only.


=== Discussion

It might be better to use the term "base URI" (as per RFC 3986) instead of "base path".




== Additional terms and notation

base path ::
an absolute IRI or a full path in the local file system
that is associated with the input source
and can be obtained by a program.




== Additional usage requirements


=== Input source

Each input source has an associated internal slot `\((base-path))`
whose value is a _character string_.

This internal slot is not accessible to a program
and need not actually exist (in any sense).
It is defined solely to aid the specification
of the semantics of words.

By default, `\((base-path))` is an empty string.

The word `restore-input` (if it is provided) shall restore `\((base-path))`
to the value it had before the corresponding call to `save-input`,
because the base path is part of the input source specification state.


==== Rationale

See also: https://forth-standard.org/standard/exception/THROW#contribution-283[Input source after THROW].
